### ISSUE TITLE
Fix Responsiveness in Contact Page

### ISSUE THREAD

**Issue by SecureSocket** [jineshnagori/DevBlog#223]

**Comment by bishwobista** [comment]
assign me

**Comment by yogeshbansal7** [comment]
please assign me this issue

**Comment by HarshikaAdarsh** [comment]
Hey @yogeshbansal7 are you still working on this, if not can you assign this issue to me?

**Comment by bishwobista** [comment]
I already fixed this, why is this  issue still open?

**Comment by anshul-132002** [comment]
Bro Why my pull request is EXLUDED  ?
